[toolchain]
package_manager = "yarn"
channel = "1.85.0"

[cli]
version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "CQCjAqpGcLs2fsvA4XoSrvYKLMEnksoTfPaxwccDVpAL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
