[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_vote_dapp = "WW4FYYUvGdGbBrF1tZRqx2d5eQpmUBZnwkPS6hLDV8T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
